# Generated by Django 4.1.3 on 2022-12-16 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendships', '0002_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friendships', to=settings.AUTH_USER_MODEL),
        ),
    ]
