version: "3.8"

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/letschat
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
