# Generated by Django 4.1.3 on 2022-11-27 15:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.get_default_image_path, max_length=255, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
