# Generated by Django 4.1.4 on 2023-01-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupchats', '0002_groupchatroommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroommessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groupchats.groupchatroom'),
        ),
    ]
