# Generated by Django 4.1.5 on 2023-01-22 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import groupchats.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupchats', '0003_alter_groupchatroommessage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='image',
            field=models.ImageField(default=groupchats.models.get_default_image_path, max_length=255, null=True, upload_to=groupchats.models.group_directory_path),
        ),
        migrations.AddField(
            model_name='groupchatroom',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
